//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Survey.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Your question has been successfully entered&quot;.
        /// </summary>
        internal static string DataIsEnterd {
            get {
                return ResourceManager.GetString("DataIsEnterd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Please enter the end caption.&quot;.
        /// </summary>
        internal static string EndCaptionEmptyMessage {
            get {
                return ResourceManager.GetString("EndCaptionEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The end caption should not contain numbers only.&quot;.
        /// </summary>
        internal static string EndCaptionJustNumberMessage {
            get {
                return ResourceManager.GetString("EndCaptionJustNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The end value must be less than 100.&quot;.
        /// </summary>
        internal static string EndValueGreaterThanOneHundredMessage {
            get {
                return ResourceManager.GetString("EndValueGreaterThanOneHundredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The end value must be greater than 0.&quot;.
        /// </summary>
        internal static string EndValueLessThanZeroMessage {
            get {
                return ResourceManager.GetString("EndValueLessThanZeroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Smomething went wrong!&quot;.
        /// </summary>
        internal static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The order must be more than 0&quot;.
        /// </summary>
        internal static string NewOrderLessThanZeroMessage {
            get {
                return ResourceManager.GetString("NewOrderLessThanZeroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Please select any question!&quot;.
        /// </summary>
        internal static string NoSelectItem {
            get {
                return ResourceManager.GetString("NoSelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Please select the question type!&quot;.
        /// </summary>
        internal static string NotChooseTheType {
            get {
                return ResourceManager.GetString("NotChooseTheType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The number of smile faces must be between 2 and 5&quot;.
        /// </summary>
        internal static string NumberOfSmileBetweenFiveAndTow {
            get {
                return ResourceManager.GetString("NumberOfSmileBetweenFiveAndTow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The number of stars must be between 1 and 10&quot;.
        /// </summary>
        internal static string NumberOfStrasBetweenTenAndOne {
            get {
                return ResourceManager.GetString("NumberOfStrasBetweenTenAndOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Please enter text&quot;.
        /// </summary>
        internal static string QuestionIsEmptyMessage {
            get {
                return ResourceManager.GetString("QuestionIsEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The text is just numbers&quot;.
        /// </summary>
        internal static string QuestionIsJustANumberMessage {
            get {
                return ResourceManager.GetString("QuestionIsJustANumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Please enter the start caption&quot;.
        /// </summary>
        internal static string StartCaptionEmptyMessage {
            get {
                return ResourceManager.GetString("StartCaptionEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The start caption should not contain numbers only&quot;.
        /// </summary>
        internal static string StartCaptionJustNumberMessage {
            get {
                return ResourceManager.GetString("StartCaptionJustNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The start value must be less than 100&quot;.
        /// </summary>
        internal static string StartValueGreaterThanOneHundredMessage {
            get {
                return ResourceManager.GetString("StartValueGreaterThanOneHundredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The start value must be greater than 0&quot;.
        /// </summary>
        internal static string StartValueLessThanZeroMessage {
            get {
                return ResourceManager.GetString("StartValueLessThanZeroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Are you sure you want to delete this question?&quot;.
        /// </summary>
        internal static string SureToDeleteMessage {
            get {
                return ResourceManager.GetString("SureToDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Your question has been edit successfully&quot;.
        /// </summary>
        internal static string TheEditMessage {
            get {
                return ResourceManager.GetString("TheEditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The end value must be greater than the start value&quot;.
        /// </summary>
        internal static string TheEndValueSholudGreaterThanStartValueMessage {
            get {
                return ResourceManager.GetString("TheEndValueSholudGreaterThanStartValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The order number is empty&quot;.
        /// </summary>
        internal static string TheOrderIsEmpty {
            get {
                return ResourceManager.GetString("TheOrderIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Your question has been delete successfully&quot;.
        /// </summary>
        internal static string TheQuestionDeleted {
            get {
                return ResourceManager.GetString("TheQuestionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Your question has not been deleted.&quot;.
        /// </summary>
        internal static string TheQuestionNotDeleted {
            get {
                return ResourceManager.GetString("TheQuestionNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Question.
        /// </summary>
        internal static string TitleOfQuestionAdd {
            get {
                return ResourceManager.GetString("TitleOfQuestionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Question.
        /// </summary>
        internal static string TitleOfQuestionEdit {
            get {
                return ResourceManager.GetString("TitleOfQuestionEdit", resourceCulture);
            }
        }
    }
}
